export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  WALLET: '/wallet',
  ADD_MONEY: '/wallet/add-money',
  WITHDRAW: '/wallet/withdraw',
  TRANSFERS: '/transfers',
  AIRTIME: '/airtime',
  DATA: '/data',
  ELECTRICITY: '/electricity',
  TV: '/tv',
  TRANSACTIONS: '/transactions',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  SUPPORT: '/support',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  SECURITY_POLICY: '/security-policy',
} as const
